# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u540d\u79f0', max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_type', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux')], max_length=32)),
                ('os_version', models.CharField(max_length=128)),
                ('public_network_addr', models.CharField(blank=True, max_length=64)),
                ('private_network_addr', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u540d\u79f0', max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('VPN', 'Virtual Private Network'), ('SSH', 'Secure Shell'), ('MSTSC', 'Windows \u8fdc\u7a0b\u5de6\u9762'), ('OTHER', '\u5176\u4ed6')], max_length=10)),
                ('access_addr', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('remark', models.TextField(blank=True)),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.OperatingSystem')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u540d\u79f0', max_length=64, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.City')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_number', models.IntegerField(help_text='CPU\u6838\u5fc3\u6570\u91cf')),
                ('memory_capacity', models.IntegerField(help_text='\u5185\u5b58\u5bb9\u91cf\uff0c\u5355\u4f4dGB')),
                ('disk_capacity', models.IntegerField(help_text='\u786c\u76d8\u5bb9\u91cf\uff0c\u5355\u4f4dGB')),
                ('device_type', models.CharField(choices=[('RM', '\u5b9e\u4f53\u673a'), ('VM', 'VM-WARE'), ('HV', 'HYPER-V'), ('VB', 'VIRTUAL-BOX'), ('OT', '\u5176\u4ed6')], max_length=2)),
                ('operating_system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storehouse.OperatingSystem')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.School')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('tel', models.CharField(blank=True, max_length=32)),
                ('qq', models.CharField(blank=True, max_length=32)),
                ('remark', models.CharField(blank=True, max_length=1024)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.School')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.Province'),
        ),
    ]
