# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystem',
            name='remark',
            field=models.CharField(blank=True, help_text='\u5907\u6ce8', max_length=128),
        ),
        migrations.AddField(
            model_name='server',
            name='remark',
            field=models.CharField(blank=True, help_text='\u5907\u6ce8', max_length=1024),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='os_type',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux')], help_text='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b', max_length=32),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='os_version',
            field=models.CharField(help_text='\u53d1\u884c\u7248', max_length=128),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='private_network_addr',
            field=models.CharField(help_text='\u5185\u7f51\u5730\u5740', max_length=64),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='public_network_addr',
            field=models.CharField(blank=True, help_text='\u516c\u7f51\u5730\u5740', max_length=64),
        ),
        migrations.AlterField(
            model_name='remoteaccess',
            name='access_addr',
            field=models.CharField(blank=True, help_text='\u8bbf\u95ee\u5730\u5740', max_length=128),
        ),
        migrations.AlterField(
            model_name='remoteaccess',
            name='access_type',
            field=models.CharField(choices=[('VPN', 'Virtual Private Network'), ('SSH', 'Secure Shell'), ('MSTSC', 'Windows \u8fdc\u7a0b\u5de6\u9762'), ('OTHER', '\u5176\u4ed6')], help_text='\u8fdc\u7a0b\u8bbf\u95ee\u65b9\u5f0f', max_length=10),
        ),
        migrations.AlterField(
            model_name='remoteaccess',
            name='operating_system',
            field=models.ForeignKey(help_text='\u64cd\u4f5c\u7cfb\u7edf', on_delete=django.db.models.deletion.CASCADE, to='storehouse.OperatingSystem'),
        ),
        migrations.AlterField(
            model_name='remoteaccess',
            name='password',
            field=models.CharField(blank=True, help_text='\u5bc6\u7801', max_length=128),
        ),
        migrations.AlterField(
            model_name='remoteaccess',
            name='remark',
            field=models.TextField(blank=True, help_text='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='remoteaccess',
            name='username',
            field=models.CharField(blank=True, help_text='\u8d26\u53f7', max_length=128),
        ),
        migrations.AlterField(
            model_name='server',
            name='device_type',
            field=models.CharField(choices=[('RM', '\u5b9e\u4f53\u673a'), ('VM', 'VM-WARE'), ('HV', 'HYPER-V'), ('VB', 'VIRTUAL-BOX'), ('OT', '\u5176\u4ed6')], help_text='\u8bbe\u5907\u7c7b\u578b', max_length=2),
        ),
        migrations.AlterField(
            model_name='server',
            name='operating_system',
            field=models.OneToOneField(help_text='\u64cd\u4f5c\u7cfb\u7edf', on_delete=django.db.models.deletion.CASCADE, to='storehouse.OperatingSystem'),
        ),
        migrations.AlterField(
            model_name='server',
            name='school',
            field=models.ForeignKey(help_text='\u5b66\u6821', on_delete=django.db.models.deletion.CASCADE, to='storehouse.School'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(help_text='\u540d\u79f0', max_length=32),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qq',
            field=models.CharField(blank=True, help_text='QQ', max_length=32),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='remark',
            field=models.CharField(blank=True, help_text='\u5907\u6ce8', max_length=1024),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tel',
            field=models.CharField(blank=True, help_text='\u7535\u8bdd', max_length=32),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, help_text='\u5934\u8854', max_length=64),
        ),
    ]
