# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0003_operatingsystem_domain_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteaccess',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='server',
            name='operating_system',
        ),
        migrations.AddField(
            model_name='remoteaccess',
            name='server_system',
            field=models.ForeignKey(default=123, help_text='\u64cd\u4f5c\u7cfb\u7edf', on_delete=django.db.models.deletion.CASCADE, to='storehouse.Server'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='domain_name',
            field=models.CharField(blank=True, help_text='\u57df\u540d', max_length=64),
        ),
        migrations.DeleteModel(
            name='OperatingSystem',
        ),
    ]
