# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0004_auto_20170712_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='os_type',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux')], default=1, help_text='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='os_version',
            field=models.CharField(default=1, help_text='\u53d1\u884c\u7248', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='private_network_addr',
            field=models.CharField(default=1, help_text='\u5185\u7f51\u5730\u5740', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='public_network_addr',
            field=models.CharField(blank=True, help_text='\u516c\u7f51\u5730\u5740', max_length=64),
        ),
    ]
