# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0005_auto_20170712_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteaccess',
            name='server_system',
        ),
        migrations.AddField(
            model_name='server',
            name='access_addr',
            field=models.CharField(blank=True, help_text='\u8bbf\u95ee\u5730\u5740', max_length=128),
        ),
        migrations.AddField(
            model_name='server',
            name='access_type',
            field=models.CharField(choices=[('VPN', 'Virtual Private Network'), ('SSH', 'Secure Shell'), ('MSTSC', 'Windows \u8fdc\u7a0b\u5de6\u9762'), ('OTHER', '\u5176\u4ed6')], default=1, help_text='\u8fdc\u7a0b\u8bbf\u95ee\u65b9\u5f0f', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='password',
            field=models.CharField(blank=True, help_text='\u5bc6\u7801', max_length=128),
        ),
        migrations.AddField(
            model_name='server',
            name='username',
            field=models.CharField(blank=True, help_text='\u8d26\u53f7', max_length=128),
        ),
        migrations.DeleteModel(
            name='RemoteAccess',
        ),
    ]
