# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0006_auto_20170719_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='os_type',
        ),
        migrations.RemoveField(
            model_name='server',
            name='os_version',
        ),
        migrations.AlterField(
            model_name='server',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.School'),
        ),
    ]
