# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0007_auto_20170719_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, help_text='\u6821\u540d', max_length=128),
        ),
        migrations.AlterField(
            model_name='server',
            name='school',
            field=models.ForeignKey(help_text='\u5b66\u6821', on_delete=django.db.models.deletion.CASCADE, to='storehouse.School'),
        ),
    ]
