# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0008_auto_20170719_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='name',
        ),
        migrations.AddField(
            model_name='server',
            name='os_type',
            field=models.CharField(blank=True, help_text='\u64cd\u4f5c\u7cfb\u7edf', max_length=32),
        ),
    ]
