# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0009_auto_20170721_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='access_type',
            field=models.CharField(blank=True, default='SSH', help_text='\u8fdc\u7a0b\u8bbf\u95ee\u65b9\u5f0f', max_length=10),
        ),
        migrations.AlterField(
            model_name='server',
            name='device_type',
            field=models.CharField(choices=[('RM', '\u5b9e\u4f53\u673a'), ('VM', 'VM-WARE')], help_text='\u8bbe\u5907\u7c7b\u578b', max_length=2),
        ),
        migrations.AlterField(
            model_name='server',
            name='remark',
            field=models.TextField(blank=True, help_text='\u5907\u6ce8', max_length=1024),
        ),
    ]
