# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0011_auto_20171115_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='manage_url',
            field=models.URLField(blank=True, help_text='\u540e\u53f0\u7ba1\u7406\u5730\u5740', max_length=128),
        ),
        migrations.AlterField(
            model_name='server',
            name='school_url',
            field=models.URLField(blank=True, help_text='\u5b66\u751f\u767b\u5f55\u5730\u5740', max_length=128),
        ),
    ]
